// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcPyV0eUKVPf6SfjDU0pxl76X5E7Am6C0',
    appId: '1:267816762017:web:6960ed630d776b15d04ee0',
    messagingSenderId: '267816762017',
    projectId: 'trackme-3d7df',
    authDomain: 'trackme-3d7df.firebaseapp.com',
    storageBucket: 'trackme-3d7df.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABx_ZZ3Jie37iBqQ8aGsE2_4wn9GB1fUs',
    appId: '1:267816762017:android:280eb5583c1f1066d04ee0',
    messagingSenderId: '267816762017',
    projectId: 'trackme-3d7df',
    storageBucket: 'trackme-3d7df.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYmTQ5p07gOELgmatE5gSxDG7mHcWSzEs',
    appId: '1:267816762017:ios:dd7bbf23c0184443d04ee0',
    messagingSenderId: '267816762017',
    projectId: 'trackme-3d7df',
    storageBucket: 'trackme-3d7df.firebasestorage.app',
    iosBundleId: 'com.example.trackme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYmTQ5p07gOELgmatE5gSxDG7mHcWSzEs',
    appId: '1:267816762017:ios:dd7bbf23c0184443d04ee0',
    messagingSenderId: '267816762017',
    projectId: 'trackme-3d7df',
    storageBucket: 'trackme-3d7df.firebasestorage.app',
    iosBundleId: 'com.example.trackme',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAcPyV0eUKVPf6SfjDU0pxl76X5E7Am6C0',
    appId: '1:267816762017:web:71990dcd2cd4c0acd04ee0',
    messagingSenderId: '267816762017',
    projectId: 'trackme-3d7df',
    authDomain: 'trackme-3d7df.firebaseapp.com',
    storageBucket: 'trackme-3d7df.firebasestorage.app',
  );
}
